################
### Language ###
################
language: java

###########
### JDK ###
###########
jdk:
  - oraclejdk11

###############
### Caching ###
###############
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

#####################
### Notifications ###
#####################
notifications:
  email: false

####################
### Build script ###
####################
script:
  - mvn clean install

##################
### Deployment ###
##################
deploy:
  provider: script
  script: mvn deploy --settings deploy/maven-settings.xml
  on:
    branch: master
    tags: true

###################
### Environment ###
###################
env:
  global:
    - NEXUS_USERNAME=deploy
    - secure: "EsuEnfAyLUu0PubolBjtYlnLCOyv6cAPu016Lk4O3akDTyDmWtpc4NlZI64jR8tcO+jR0XnwotQbR+/FkYrCv0zk/TwrIlajCJ227aUKVmDnioHS5qSC2nSHF0gW8ayPR5sxE8uJb3VqJP+l45v91kg3rehqLrBlOAlnYGSloR8Jt9FR7Ii3ombRUul7TdN0ddH+U6F82u2+S8t8TQ7feZ2vwVEE1zmmFLbqC7xCzbmdNeGoCwloBND2QH7lhpcy0ezrWEDjwTivuLIcL6sQYBfbZv9hnOkYgwhPYWQ2iZgvB80/+5/BrD7Xq7OoUlRaeBkO83ZKJwJ0Dmox5nRfiFTibe1ZuYUYLp0CQUyuP1pn1yMlB3g61D3rmrBsSmX/jHBqfXwGU+MlLfd97N//LL+RCIPLvZKcH9JEv+6BIHbdANbm1Qig3wJSEN6gAhK2GcmRNuVpkDwyzZXwOW7hBbTnsyChNQW8ijN4A47fflSH+S3gYozk7XT31uXAdFVoo7ILe/tBGELN/l9yXhWrrgDHrfvZycSalJrMvSePCf/OEd2O1omDu+t/wyyl53xwadSyGn4AoVbqPwJ8ryzuZauohPAhMybLIAkpuGiAQ1Q295kuYBKnU4ui8OdZXqXWwZnjE6JBVxjyBVol/GvTNSFHOdaJsVkquO3kTgEzRb8="
